Repository thelounge/thelounge, pull requests merged in 2018-06, with the labels that each got.

#2388 Fix Alt+Up/Down cycling through channels of collapsed networks
  client/js/keybinds.js
Labels: Type: Bug

#2502 Undo webpack sorting, it made network always locked
  webpack.config.js
Labels: Type: Bug

#2503 Prevent long lobby names pushing badges out of sidebar
  client/css/style.css
Labels: Type: Bug

#2505 Don't mark your nick changes as self in each channel
  src/plugins/irc-events/nick.js
Labels: Type: Bug

#2504 If a preview fails to load, remove the link from msg object
  src/plugins/irc-events/link.js
Labels: Type: Bug

#2508 Do not write topic on join to logs
  src/models/msg.js
Labels: Type: Feature

#2510 Make CTCP requests/responses increase unread counter
  src/plugins/irc-events/ctcp.js
Labels: Type: Feature

#2530 Fix adding a new network expanding collapsed networks incorrectly
  client/js/render.js
Labels: Type: Bug

#2114 Allow connecting/disconnecting from networks in UI, closes #631
  client/css/style.css
  client/js/contextMenuFactory.js
  client/js/lounge.js
  client/js/utils.js
Labels: Type: Feature

#2534 Fix word boundary in the custom highlights regex not matching unicode
  client/js/options.js
Labels: Type: Bug

#2535 Set caching on shields.io badges in readme
  README.md
Labels: Type: Documentation

#2539 Restore whitespace between caret and More/Less text in previews
  client/css/style.css
Labels: Type: Bug

#2541 Mark sqlite3 as an optional dependency
  package.json
Labels: Type: Bug

#2538 De-duplicate link fetching to one request at once
  src/plugins/irc-events/link.js
  test/plugins/link.js
Labels: Type: Feature

#2546 Fix sqlite history not loading when maxHistory is -1
  src/plugins/messageStorage/sqlite.js
Labels: Type: Bug

#2547 Synchronise number of highlighted messages to client
  client/js/lounge.js
  client/js/socket-events/msg.js
  client/js/socket-events/open.js
  client/views/chan.tpl
  src/models/chan.js
Labels: Type: Bug

#2544 Remove label on force sync button
  client/views/windows/settings.tpl
Labels: Type: Bug

#2540 Make non-highlighted favicon look more different than highlighted one
  client/img/favicon-normal.ico
Labels: Type: Feature

#2501 Improve formatting of text logs
  src/plugins/messageStorage/text.js
Labels: Type: Feature

#2558 Fix undefined channel when updating title
  client/js/utils.js
Labels: Type: Bug

#2564 Move .nyc_output folder out of root
  .gitignore
  test/.nycrc-mocha
  test/.nycrc-mocha-webpack
  test/.nycrc-report
Labels: Meta: Internal

#2565 Target more modern browsers in babel
  webpack.config.js
Labels: Type: Feature

#2567 Do not remove date marker when loading history if date changes
  client/js/socket-events/more.js
Labels: Type: Bug

#2569 Fix circular dependency in Helper+log
  src/helper.js
  src/log.js
  src/plugins/messageStorage/text.js
  test/src/helperTest.js
Labels: Type: Bug

#2523 Display visual feedback on self away/back
  client/views/actions/away.tpl
  client/views/actions/back.tpl
  src/plugins/irc-events/away.js
Labels: Type: Feature

#2554 WHOWAS support
  client/views/actions/whois.tpl
  src/plugins/irc-events/whois.js
Labels: Type: Feature

#2580 Reset highlights on self messages; update title when other client opens a channel
  client/js/socket-events/msg.js
  client/js/socket-events/open.js
Labels: Type: Bug

#2576 Also send away notices to query windows
  src/plugins/irc-events/away.js
Labels: Type: Feature

#2548 Fix text not having enough space in <select> with some fonts
  client/css/style.css
  client/index.html.tpl
  client/themes/morning.css
Labels: Type: Bug

#2526 Replace current red-text highlight with a full background-color highlight
  client/css/style.css
  client/themes/morning.css
Labels: Type: Feature

#2585 Fix highlights when seconds are shown in timestamps
  client/css/style.css
Labels: Type: Bug

#2592 Update `no-confusing-error` eslint rule to allow parenthesis
  .eslintrc.yml
Labels: Meta: Internal

#2603 add `.github` folder
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/SUPPORT.md
Labels: Type: Documentation
