Repository thelounge/thelounge, pull requests merged in 2018-12, with the labels that each got.

#2915 Fix spelling mistake in defaults/config.js
  defaults/config.js
Labels: Type: Documentation

#2786 Update changelog generator script
  scripts/changelog.js
Labels: Meta: Internal

#2930 Add logging to all code paths in LDAP auth
  src/plugins/auth/ldap.js
Labels: Type: Feature
