Repository thelounge/thelounge, pull requests merged in 2018-08, with the labels that each got.

#2677 Fix irc modifiers not working with caps lock
  client/js/keybinds.js
Labels: Type: Bug

#2695 Add X-Purpose header to link prefetcher
  src/plugins/irc-events/link.js
Labels: Type: Feature

#2683 Keep timestamps aligned when using a font with variable-width numbers
  client/css/style.css
Labels: Type: Feature

#2702 Fix bugs with URL overrides in Connect window
  client/js/socket-events/configuration.js
  src/server.js
Labels: Type: Bug

#2601 Make menu state consistent on desktop and mobile; fix sliding on desktop
  client/css/style.css
  client/js/slideout.js
  client/js/socket-events/init.js
  client/themes/default.css
Labels: Type: Bug

#2716 Use a new npmjs token to publish through Travis
  .travis.yml
Labels: Meta: Internal

#2718 Remember disconnected networks between server restarts
  src/client.js
  src/models/network.js
  src/plugins/inputs/connect.js
  src/plugins/inputs/disconnect.js
  test/models/network.js
Labels: Type: Feature

#2721 Fix displaying away message multiple times in query windows
  src/plugins/irc-events/away.js
Labels: Type: Bug

#2730 Make sure data is an object
  src/server.js
Labels: Type: Bug
