Repository thelounge/thelounge, pull requests merged in 2018-07, with the labels that each got.

#2613 Add reminder that ascii is awesome
  client/js/libs/handlebars/colorClass.js
Labels: Meta: Internal, Meta: Skip Changelog

#2570 Warn if config owner doesn't match process uid
  src/command-line/index.js
Labels: Type: Feature

#2621 Fix link to contributing instructions in readme
  README.md
Labels: Type: Bug, Type: Documentation

#2595 Clarify /topic command without newtopic
  client/views/windows/help.tpl
Labels: Type: Documentation, Type: Feature

#2571 Implement irc:// protocol handler
  client/js/options.js
  client/js/socket-events/configuration.js
  client/views/windows/settings.tpl
Labels: Type: Feature

#2599 Make userlist state consistent on mobile and desktop
  client/css/style.css
  client/js/lounge.js
  client/js/socket-events/init.js
Labels: Type: Bug

#2626 Fix incorrect target in (dis)connect context menu
  client/js/contextMenuFactory.js
Labels: Type: Bug

#2624 Increase delay between links to remove random test failure
  test/plugins/link.js
Labels: Meta: Internal, Type: Bug

#2609 Stop handling CTCP messages if the sender/target is ignored
  src/plugins/irc-events/ctcp.js
Labels: Type: Feature

#2604 Introduce issue templates
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
Labels: Type: Documentation

#2630 Fix disabling autocomplete and fix completing special channels
  client/js/autocompletion.js
Labels: Type: Bug

#2622 Fix incorrect left padding for highlights on mobile
  client/css/style.css
Labels: Type: Bug

#2639 Remove extra closing tag
  client/views/msg_preview.tpl
Labels: Type: Bug

#2637 Do not write /list messages to logs
  src/models/msg.js
Labels: Type: Bug

#2640 Fix ignore list resetting on server restart
  src/client.js
  src/server.js
Labels: Type: Bug

#2633 Make the MOTDs a little nicer if possible
  client/js/render.js
Labels: Type: Feature

#2657 use replace over trimEnd to support ff60
  client/js/render.js
Labels: Type: Bug

#2664 Recommend using Yarn instead of NPM in changelog and readme
  README.md
  scripts/changelog.js
Labels: Type: Documentation

#2645 Improve inline documentation of config defaults and use it to generate website counterpart
  defaults/config.js
  scripts/generate-config-doc.js
Labels: Type: Feature

#2670 Don't put .log in text log folder name
  src/plugins/messageStorage/text.js
Labels: Type: Bug

#2669 refactor getHumanDate() to accept a timestamp; avoids possible test failure; more accurate log times
  src/log.js
  src/plugins/messageStorage/text.js
  test/src/helperTest.js
Labels: Meta: Internal

#2643 Make userlist section titles sticky on scroll, improve contrasts for accessibility, use CSS variables
  client/css/style.css
  client/js/utils.js
  client/themes/morning.css
  client/views/user.tpl
Labels: Type: Feature

#2515 Network-first service worker caches
  client/css/bootstrap.css
  client/js/loading-error-handlers.js
  client/js/socket-events/configuration.js
  client/service-worker.js
  client/views/windows/settings.tpl
  src/server.js
Labels: Type: Feature
