Repository thelounge/thelounge, pull requests merged in 2018-04, with the labels that each got.

#2321 Fix .container margins
  client/css/style.css
Labels: Type: Feature

#2331 Fix line-height showing scrollbar on mobile
  client/css/style.css
Labels: Type: Bug

#2335 Update sinon to the latest version
  package.json
  yarn.lock
Labels: Meta: Internal, greenkeeper

#2117 Upgrade to webpack 4; tracking pr
  client/css/fontawesome.css
  client/css/style.css
  client/index.html.tpl
  package.json
  src/command-line/index.js
  webpack.config-browser.js
  webpack.config-test.js
  webpack.config.js
  yarn.lock
Labels: Meta: Internal

#2340 Prevent "undefined" OS version in session list
  src/client.js
Labels: Type: Bug

#2344 Replace client ids with guids
  src/client.js
  src/plugins/irc-events/connection.js
Labels: Meta: Internal

#2317 Enable sync on empty localstorage, force sync, sync on both load and reconnect.
  client/js/options.js
  client/js/socket-events/configuration.js
  client/js/socket-events/setting.js
  client/views/windows/settings.tpl
Labels: Type: Bug

#2349 Fix previews on Morning (and others)
  client/css/style.css
  client/themes/morning.css
Labels: Type: Bug

#2229 Allow editing networks via UI
  client/css/style.css
  client/js/contextMenuFactory.js
  client/js/lounge.js
  client/js/socket-events/changelog.js
  client/js/socket-events/configuration.js
  client/js/socket-events/network.js
  client/views/windows/connect.tpl
  src/client.js
  src/helper.js
  src/models/network.js
  src/plugins/irc-events/error.js
  src/server.js
  test/models/network.js
  test/server.js
Labels: Type: Feature

#2363 Fix nicks with special characters being colored incorrectly in messages
  client/js/libs/handlebars/parse.js
Labels: Type: Bug

#2367 Quick-fix tooltips not being loaded by Webpack
  client/css/style.css
  client/index.html.tpl
  webpack.config.js
Labels: Type: Bug

#2368 Remove header border on non-chat windows and reduce top margin a bit more
  client/css/style.css
  client/themes/morning.css
Labels: Type: Feature

#2369 Make "Show older messages" style consistent with other buttons
  client/css/style.css
  client/js/render.js
  client/js/socket-events/init.js
  client/js/socket-events/more.js
  client/js/socket.js
  client/themes/morning.css
  client/views/chat.tpl
Labels: Type: Feature

#2355 Add 'op' and 'voice' user context menu items
  client/css/style.css
  client/js/contextMenuFactory.js
  client/js/utils.js
Labels: Type: Feature

#2385 Make a separate function to execute yarn commands; fallback to global yarn
  src/command-line/install.js
  src/command-line/uninstall.js
  src/command-line/utils.js
Labels: Type: Bug

#2392 Correctly add quits to parts
  client/js/condensed.js
Labels: Type: Bug

#2387 Run Travis CI against Node v10
  .travis.yml
  package.json
  yarn.lock
Labels: Meta: Internal

#2009 Favicons, favicons everywhere
  client/img/apple-touch-icon-120x120.png
  client/img/favicon-alerted.ico
  client/img/favicon-normal.ico
  client/img/favicon-notification.png
  client/img/favicon.png
  client/img/icon-alerted-black-transparent-bg-72x72px.png
  client/img/icon-alerted-grey-bg-192x192px.png
  client/img/icon-black-transparent-bg.svg
  client/img/logo-64.png
  client/img/logo-dark.svg
  client/img/logo-grey-bg-120x120px.png
  client/img/logo-grey-bg-152x152px.png
  client/img/logo-grey-bg-167x167px.png
  client/img/logo-grey-bg-180x180px.png
  client/img/logo-grey-bg-192x192px.png
  client/img/logo-grey-bg.svg
  client/img/logo.svg
  client/img/touch-icon-192x192.png
  client/index.html.tpl
  client/js/socket-events/msg.js
  client/manifest.json
  client/service-worker.js
  test/plugins/link.js
  test/plugins/storage.js
Labels: Type: Feature

#2398 Use attr() on user-controlled data
  client/js/contextMenu.js
  client/js/contextMenuFactory.js
  client/js/lounge.js
  client/js/options.js
  client/js/render.js
  client/js/socket-events/nick.js
  client/js/socket-events/quit.js
  client/js/utils.js
Labels: Type: Bug, Type: Security

#2399 Fix `aria-controls` on collapse button
  client/views/chan.tpl
  client/views/network.tpl
Labels: Type: Bug

#2380 Add `upgrade` CLI command for themes and packages
  src/command-line/index.js
  src/command-line/upgrade.js
Labels: Type: Feature
