Repository thelounge/thelounge, pull requests merged in 2018-02, with the labels that each got.

#2035 Ensure packages loaded are directories
  src/command-line/install.js
  src/command-line/uninstall.js
  src/helper.js
  src/plugins/packages/index.js
  test/fixtures/.gitignore
  test/fixtures/.lounge/packages/node_modules/thelounge-package-foo/index.js
  test/fixtures/.lounge/packages/node_modules/thelounge-package-foo/package.json
  test/fixtures/.lounge/packages/package.json
  test/plugins/packages/indexTest.js
  test/util.js
Labels: Type: Bug

#2021 Use forked ldapjs to remove dtrace
  package.json
  src/plugins/auth/ldap.js
  test/plugins/auth/ldap.js
Labels: Meta: Internal

#1933 Show channel name on channel-related errors
  src/plugins/irc-events/error.js
Labels: Type: Feature

#2060 Fix themes not loading
  src/plugins/packages/index.js
Labels: Type: Bug

#2055 Fix border after nickname not taking full height
  client/css/style.css
  client/themes/morning.css
  client/themes/zenburn.css
  src/plugins/irc-events/motd.js
Labels: Type: Bug

#2058 Track channel state to allow removing channels user is not in
  src/models/chan.js
  src/plugins/inputs/part.js
  src/plugins/irc-events/connection.js
  src/plugins/irc-events/join.js
  src/plugins/irc-events/kick.js
  test/models/chan.js
Labels: Type: Bug

#1910 Allow scaling the page
  client/index.html.tpl
Labels: Type: Bug

#2071 Fix bind not being passed to irc-framework
  src/client.js
Labels: Type: Bug

#2072 Add changelog entry for v2.7.1
  CHANGELOG.md
Labels: Meta: Skip Changelog

#1760 Get rid of `Object.assign` polyfill
  client/js/libs/handlebars/ircmessageparser/merge.js
Labels: Type: Feature

#1915 Turn channel list into an accessible tablist
  client/index.html.tpl
  client/js/autocompletion.js
  client/js/join-channel.js
  client/js/lounge.js
  client/js/socket-events/msg.js
  client/js/utils.js
  client/views/chan.tpl
  client/views/chat.tpl
Labels: Type: Feature

#1727 Switch to Node v6 as the minimal supported version
  .eslintrc.yml
  .travis.yml
  appveyor.yml
  client/js/webpush.js
  index.js
  package.json
  scripts/generate-emoji.js
  src/client.js
  src/command-line/index.js
  src/command-line/users/add.js
  src/command-line/users/edit.js
  src/command-line/users/reset.js
  src/log.js
  src/plugins/inputs/action.js
  src/plugins/inputs/ban.js
  src/plugins/inputs/connect.js
  src/plugins/inputs/ctcp.js
  src/plugins/inputs/disconnect.js
  src/plugins/inputs/invite.js
  src/plugins/inputs/kick.js
  src/plugins/inputs/list.js
  src/plugins/inputs/mode.js
  src/plugins/inputs/query.js
  src/plugins/inputs/raw.js
  src/plugins/inputs/rejoin.js
  src/plugins/inputs/topic.js
  src/plugins/inputs/whois.js
  src/plugins/irc-events/message.js
  src/plugins/irc-events/mode.js
  src/plugins/webpush.js
  test/commands/mode.js
  test/util.js
  webpack.config.js
Labels: Type: Deprecation

#2059 Render MOTD with a single message
  client/js/constants.js
  client/js/libs/handlebars/ircmessageparser/parseStyle.js
  client/js/render.js
  src/plugins/irc-events/motd.js
  test/client/js/constantsTest.js
  test/client/js/libs/handlebars/parse.js
Labels: Type: Feature

#2076 Skip scripts folder from test coverage
  .nycrc
Labels: Meta: Internal

#1919 Show error if image is greater than max prefetch size
  client/css/style.css
  client/js/libs/handlebars/friendlysize.js
  client/views/msg_preview.tpl
  src/plugins/irc-events/link.js
  test/client/js/libs/handlebars/friendlysizeTest.js
Labels: Type: Feature

#1728 Remove autoload deprecation notice
  src/clientManager.js
Labels: Type: Deprecation

#1729 Remove deprecated support for `debug` as a boolean in the configuration file
  src/helper.js
Labels: Type: Deprecation

#1733 Remove deprecated support for the `--home` option and `$LOUNGE_HOME` environment variable
  src/command-line/index.js
Labels: Meta: Do Not Merge, Type: Deprecation

#1927 Fix CTCP commands always sent upper-case
  src/plugins/inputs/ctcp.js
Labels: Meta: Do Not Merge, Type: Bug

#1834 Remove deprecated options for `thelounge start`
  src/command-line/start.js
Labels: Type: Deprecation

#1966 Remove session token hash conversion
  src/client.js
Labels: Type: Deprecation

#1730 Remove deprecated support for CSS filenames in theme configuration
  client/index.html.tpl
  client/js/options.js
  src/helper.js
Labels: Type: Deprecation

#1980 Replace reference to website with new URL
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  client/themes/crypto.css
  client/themes/morning.css
  client/themes/zenburn.css
  client/views/windows/help.tpl
  defaults/config.js
  package.json
  scripts/changelog.js
  test/client/js/libs/handlebars/ircmessageparser/findLinks.js
  test/client/js/libs/handlebars/parse.js
  test/models/msg.js
Labels: Type: Documentation

#2049 Sync network status and security to client UI
  client/css/style.css
  client/js/socket-events/network.js
  client/views/network.tpl
  src/models/network.js
  src/plugins/irc-events/connection.js
  test/models/network.js
Labels: Type: Feature, Type: Security

#2031 Improve monospace formatting in messages
  client/css/style.css
Labels: Type: Feature

#1962 Enable no-var rule
  .eslintrc.yml
  client/js/libs/handlebars/colorClass.js
  client/js/libs/handlebars/diff.js
  client/js/libs/handlebars/modes.js
  client/js/libs/slideout.js
  client/js/loading-error-handlers.js
  client/js/lounge.js
  client/js/options.js
  client/js/render.js
  client/js/socket-events/msg.js
  client/js/utils.js
  index.js
  src/client.js
  src/command-line/config.js
  src/command-line/users/add.js
  src/command-line/users/edit.js
  src/command-line/users/reset.js
  src/helper.js
  src/identification.js
  src/log.js
  src/models/chan.js
  src/models/msg.js
  src/models/network.js
  src/models/user.js
  src/plugins/inputs/action.js
  src/plugins/inputs/ban.js
  src/plugins/inputs/connect.js
  src/plugins/inputs/disconnect.js
  src/plugins/inputs/invite.js
  src/plugins/inputs/kick.js
  src/plugins/inputs/mode.js
  src/plugins/inputs/msg.js
  src/plugins/inputs/nick.js
  src/plugins/inputs/notice.js
  src/plugins/inputs/part.js
  src/plugins/inputs/query.js
  src/plugins/inputs/quit.js
  src/plugins/inputs/rejoin.js
  src/plugins/inputs/topic.js
  src/plugins/irc-events/link.js
  src/server.js
  src/userLog.js
  test/commands/mode.js
  test/fixtures/env.js
  test/models/chan.js
  test/models/network.js
  test/tests/nickhighlights.js
  test/util.js
Labels: Meta: Internal

#2077 Remove support for the `lounge` CLI (which was replaced with `thelounge`)
  package.json
  src/command-line/index.js
Labels: Type: Deprecation

#2003 Add logo to README, and make intro it look a little nicer
  README.md
  client/img/logo-vertical-transparent-bg.svg
Labels: Type: Documentation

#1734 Switch default home location to `~/.thelounge`
  .thelounge_home
  src/command-line/utils.js
  test/fixtures/.gitignore
  test/fixtures/.thelounge/config.js
  test/fixtures/.thelounge/packages/node_modules/thelounge-package-foo/index.js
  test/fixtures/.thelounge/packages/node_modules/thelounge-package-foo/package.json
  test/fixtures/.thelounge/packages/package.json
  test/fixtures/.thelounge/vapid.json
  test/fixtures/env.js
Labels: Type: Feature

#2078 Fix active class not being removed when switching channels
  client/js/lounge.js
Labels: Type: Bug

#1928 Rewrite ctcp handling
  src/client.js
  src/plugins/irc-events/ctcp.js
Labels: Type: Bug

#2079 Add titles to all windows
  client/index.html.tpl
Labels: Type: Bug

#2080 Deal with npm's `dist-tag` at Travis deploy time
  .travis.yml
Labels: Meta: Internal

#1920 Enforce padding-line-between-statements
  .eslintrc.yml
  client/js/autocompletion.js
  client/js/condensed.js
  client/js/join-channel.js
  client/js/libs/handlebars/colorClass.js
  client/js/libs/handlebars/ircmessageparser/fill.js
  client/js/libs/handlebars/ircmessageparser/findNames.js
  client/js/libs/handlebars/ircmessageparser/parseStyle.js
  client/js/libs/handlebars/parse.js
  client/js/loading-error-handlers.js
  client/js/lounge.js
  client/js/options.js
  client/js/renderPreview.js
  client/js/socket-events/change_password.js
  client/js/socket-events/more.js
  client/js/socket-events/msg.js
  client/js/socket-events/nick.js
  client/js/utils.js
  client/views/index.js
  index.js
  scripts/changelog.js
  src/client.js
  src/clientManager.js
  src/command-line/index.js
  src/command-line/uninstall.js
  src/command-line/users/add.js
  src/command-line/users/edit.js
  src/command-line/users/reset.js
  src/command-line/utils.js
  src/helper.js
  src/models/network.js
  src/plugins/auth/ldap.js
  src/plugins/changelog.js
  src/plugins/inputs/msg.js
  src/plugins/inputs/query.js
  src/plugins/inputs/topic.js
  src/plugins/irc-events/banlist.js
  src/plugins/irc-events/link.js
  src/plugins/irc-events/message.js
  src/plugins/irc-events/mode.js
  src/plugins/irc-events/names.js
  src/plugins/irc-events/whois.js
  src/plugins/packages/themes.js
  src/server.js
  src/userLog.js
  test/plugins/auth/ldap.js
  test/plugins/packages/indexTest.js
  test/server.js
  test/util.js
Labels: Meta: Internal

#1987 Switch from npm to yarn
  .gitignore
  .travis.yml
  README.md
  appveyor.yml
  package.json
  src/command-line/install.js
  src/command-line/uninstall.js
  yarn.lock
Labels: Type: Documentation, Type: Feature

#1726 Instrument client code before running tests
  .nycrc
  appveyor.yml
  package.json
  test/.nycrc-mocha
  test/.nycrc-mocha-webpack
  test/.nycrc-report
  test/mocha-webpack.opts
  test/mocha.opts
  webpack.config-test.js
  yarn.lock
Labels: Meta: Internal, Type: Feature

#2085 Fix badge links in README going over the images
  README.md
Labels: Type: Documentation

#2086 Update Node version required in README
  README.md
Labels: Type: Documentation

#2087 Do not publish Webpack config for test env
  .npmignore
Labels: Meta: Internal

#2081 Consider localhost connections secure
  src/models/network.js
Labels: Type: Security

#1918 relay client's preferred language in link preview requests
  src/plugins/irc-events/link.js
  src/server.js
  test/plugins/link.js
Labels: Type: Feature

#2088 Ignore events on the server if incorrect data is supplied
  src/server.js
Labels: Type: Security

#2091 Update all links to thelounge repository
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  client/css/style.css
  client/js/renderPreview.js
  client/service-worker.js
  client/views/windows/changelog.tpl
  client/views/windows/help.tpl
  package.json
  scripts/changelog.js
  scripts/run-pr.sh
  src/clientManager.js
  src/models/chan.js
  src/models/user.js
  src/plugins/changelog.js
  src/plugins/irc-events/link.js
  src/plugins/webpush.js
  test/client/js/libs/handlebars/parse.js
  test/models/msg.js
Labels: Meta: Internal

#2082 Remove isRegistered
  src/client.js
  src/server.js
Labels: Meta: Internal

#2093 Use Yarn in the PR-test script
  scripts/run-pr.sh
Labels: Meta: Internal

#2095 Send empty banlist error to lobby for channels user is not in
  src/plugins/irc-events/banlist.js
Labels: Type: Bug

#2090 Allow generating random numbers in nick on page load
  defaults/config.js
  src/server.js
Labels: Type: Feature

#2099 Change wsEngine to "ws"
  src/server.js
Labels: Type: Bug

#2110 Use document.body when wrapping it in a jquery object
  client/js/lounge.js
  client/js/socket-events/init.js
  client/js/utils.js
Labels: Meta: Internal

#2106 Fix log.warn in ldap
  src/plugins/auth/ldap.js
Labels: Type: Bug

#2102 Back to help wanted label
  CONTRIBUTING.md
Labels: Type: Documentation

#2101 Word prefetch errors differently
  client/views/msg_preview.tpl
Labels: Type: Feature

#2107 Always correctly trigger sticky scroll on .chat container
  client/js/render.js
  client/js/renderPreview.js
  client/js/socket-events/msg.js
Labels: Type: Bug

#2109 Fix "rendering..." getting stuck on first connection
  client/js/socket-events/init.js
Labels: Type: Bug

#2098 Enable logging for LDAP users
  src/clientManager.js
  src/plugins/auth/ldap.js
Labels: Type: Feature

#2094 Enable in-browser run of client testing
  package.json
  test/client/index.html
  test/client/index.js
  webpack.config-browser.js
  yarn.lock
Labels: Meta: Internal

#2115 Channel leave button tooltip to correspond with right click context menu
  client/views/chan.tpl
Labels: Type: Bug

#2122 Revert "Allow scaling the page"
  client/index.html.tpl
Labels: Type: Bug

#2121 Point download badge to npm-stat instead of npm
  README.md
Labels: Type: Documentation

#2113 Refactor channel titles to use flexbox
  client/css/style.css
  client/views/chat.tpl
Labels: Type: Feature

#2108 Log socket close error if any
  src/plugins/irc-events/connection.js
Labels: Type: Feature

#1907 Add log role to message container
  client/views/chat.tpl
Labels: Type: Feature

#2132 Remove unintentionally included lodash in client build
  client/js/condensed.js
Labels: Meta: Internal

#1669 add autocompleted names to private chats
  client/js/autocompletion.js
Labels: Type: Feature

#2134 Increase test timeout on CI
  test/server.js
Labels: Meta: Skip Changelog
