Repository thelounge/thelounge, pull requests merged in 2018-09, with the labels that each got.

#2733 Enforce lobby to be the 0th channel when sorting
  src/client.js
Labels: Type: Bug

#2737 Update screenshot in readme
  README.md
Labels: Type: Documentation

#2741 Fix passwords not being saved in Firefox
  client/views/windows/sign_in.tpl
  src/server.js
Labels: Type: Bug

#2552 Add file uploading support
  client/css/style.css
  client/index.html.tpl
  client/js/socket-events/configuration.js
  client/js/socket-events/index.js
  client/js/socket-events/uploads.js
  client/js/socket.js
  client/js/upload.js
  defaults/config.js
  package.json
  src/helper.js
  src/plugins/uploader.js
  src/server.js
  yarn.lock
Labels: Type: Feature

#2751 Fix stacktraces in client tests
  webpack.config-test.js
Labels: Meta: Internal

#2748 Only emit upload url to the client that uploaded the file
  src/plugins/uploader.js
  src/server.js
Labels: Type: Bug

#2749 Move correct file after upload, put file extension in slug
  src/plugins/uploader.js
Labels: Type: Bug, Type: Security

#2775 Fix fullscreen mode for videos.
  client/css/style.css
Labels: Type: Bug

#2618 Enable underlines on links
  client/css/style.css
Labels: Type: Feature

#2788 Remove moment locales from build
  webpack.config.js
Labels: Meta: Internal

#2790 Add hover underline on preview expand button
  client/css/style.css
Labels: Type: Feature

#2792 Remove Node.js v9 from the Travis CI matrix
  .travis.yml
Labels: Type: Deprecation, Type: Feature

#2795 Fix issues in regards to ignoring your own nickname
  src/plugins/inputs/msg.js
  src/plugins/irc-events/message.js
Labels: Type: Bug
