Repository thelounge/thelounge, pull requests merged in 2018-03, with the labels that each got.

#2135 Make code blocks more readable in darker themes
  client/themes/morning.css
  client/themes/zenburn.css
Labels: Type: Feature

#2133 Change ctrl/command up/down to alt/option up/down to align with other apps
  client/js/keybinds.js
  client/views/windows/help.tpl
Labels: Type: Feature

#2140 Bring back line-height on messages
  client/css/style.css
Labels: Type: Bug

#2142 Set channel state to joined when channel already exists
  src/plugins/irc-events/join.js
Labels: Type: Bug

#2144 Warn about old config folder
  src/command-line/index.js
  src/command-line/utils.js
Labels: Type: Deprecation

#1842 Move the user list client code to its own file and make it possible to navigate with keyboard
  client/css/style.css
  client/js/lounge.js
  client/js/render.js
  client/js/userlist.js
Labels: Type: Feature

#2145 Replace colors.js with chalk
  package.json
  scripts/changelog.js
  src/client.js
  src/clientManager.js
  src/command-line/config.js
  src/command-line/index.js
  src/command-line/install.js
  src/command-line/start.js
  src/command-line/uninstall.js
  src/command-line/users/add.js
  src/command-line/users/edit.js
  src/command-line/users/list.js
  src/command-line/users/remove.js
  src/command-line/users/reset.js
  src/command-line/utils.js
  src/helper.js
  src/identification.js
  src/log.js
  src/plugins/auth/local.js
  src/plugins/packages/index.js
  src/server.js
  yarn.lock
Labels: Meta: Internal

#1668 Center loading screen and add logo
  client/css/style.css
  client/img/logo-vertical-transparent-bg.svg
  client/img/logo-vertical-transparent-dark.svg
  client/index.html.tpl
  client/js/loading-error-handlers.js
  client/themes/morning.css
  client/themes/zenburn.css
Labels: Type: Feature

#1867 Add support for collapsing networks
  client/css/style.css
  client/js/render.js
  client/js/socket-events/join.js
  client/js/socket-events/quit.js
  client/js/socket-events/sync_sort.js
  client/themes/crypto.css
  client/views/network.tpl
Labels: Type: Feature

#2143 Do not crash when user file can not be read or written
  src/clientManager.js
Labels: Type: Bug

#2075 Allow setting `rejectUnauthorized` per network
  client/views/windows/connect.tpl
  defaults/config.js
  src/client.js
  src/models/network.js
  test/models/network.js
Labels: Type: Security

#2154 Fix rejectUnauthorized
  client/views/windows/connect.tpl
  src/client.js
Labels: Type: Bug

#2150 Cleanup chat/userlist to use flexbox, fix a couple of bugs
  client/css/style.css
  client/js/autocompletion.js
  client/js/lounge.js
  client/js/render.js
  client/js/socket-events/msg.js
  client/js/userlist.js
  client/js/utils.js
  client/themes/crypto.css
  client/themes/morning.css
  client/themes/zenburn.css
  client/views/chat.tpl
Labels: Type: Bug

#2160 Fix chat and userlist not scrolling
  client/css/style.css
Labels: Type: Bug

#2156 Update chalk to the latest version
  package.json
  yarn.lock
Labels: greenkeeper

#2163 Apply ECDH curve fix only on affected version
  src/plugins/irc-events/link.js
Labels: Type: Bug

#2164 Remove setMaxListeners
  src/plugins/irc-events/link.js
Labels: Meta: Internal

#2158 Do not listen to touch events until client is initialized
  client/js/libs/slideout.js
  client/js/lounge.js
  client/js/slideout.js
  client/js/socket-events/init.js
Labels: Type: Bug

#2161 Add install command support for package version
  src/command-line/install.js
Labels: Type: Feature

#2149 Cleanup sidebar to use flexbox
  client/css/style.css
  client/js/render.js
  client/js/socket-events/join.js
  client/js/socket-events/quit.js
  client/js/socket-events/sync_sort.js
  client/views/chan.tpl
  client/views/network.tpl
Labels: Meta: Internal

#2170 Optimized notification dot state
  client/css/style.css
  client/js/utils.js
Labels: Meta: Internal

#2171 Normalize unicode URLs in link prefetcher
  src/plugins/irc-events/link.js
  test/plugins/link.js
Labels: Type: Bug

#2172 Fix background color when hovering users in user list (darker themes)
  client/themes/morning.css
  client/themes/zenburn.css
Labels: Type: Bug

#2166 Scroll to joined/activated channel
  client/js/lounge.js
  client/js/userlist.js
  client/js/utils.js
Labels: Type: Feature

#1839 Add sqlite logging and reloading messages
  defaults/config.js
  package.json
  src/client.js
  src/models/chan.js
  src/models/msg.js
  src/models/network.js
  src/plugins/inputs/query.js
  src/plugins/irc-events/join.js
  src/plugins/irc-events/message.js
  src/plugins/irc-events/whois.js
  src/plugins/sqlite.js
  src/server.js
  test/fixtures/.gitignore
  test/models/network.js
  test/plugins/sqlite.js
  yarn.lock
Labels: Type: Feature

#2177 Always hide horizontal overflow in chat
  client/css/style.css
Labels: Type: Bug

#2179 Do not include colon in push message for actions
  src/plugins/irc-events/message.js
Labels: Type: Bug

#1851 Optional syncing of client settings.
  client/css/style.css
  client/js/autocompletion.js
  client/js/libs/handlebars/tz.js
  client/js/options.js
  client/js/socket-events/configuration.js
  client/js/socket-events/index.js
  client/js/socket-events/msg.js
  client/js/socket-events/setting.js
  client/js/sorting.js
  client/views/windows/settings.tpl
  src/clientManager.js
  src/server.js
Labels: Type: Feature

#2181 Do not crash when awayMessage is set but IRC connection does not exist
  src/client.js
Labels: Type: Bug

#2180 Try to fix sqlite test failing on CI randomly
  test/plugins/sqlite.js
Labels: Meta: Internal

#2182 Remove `contain` as it's causing rendering issues
  client/css/style.css
Labels: Type: Bug

#2188 Only request znc.in/playback if sqlite logging is enabled
  src/client.js
Labels: Type: Bug

#2189 Allow overriding arrays in config, warn about incorrect types
  src/helper.js
  test/tests/mergeConfig.js
Labels: Type: Bug

#2192 Don't access "Notification" if the browser does not support it
  client/js/options.js
Labels: Type: Bug

#2190 Close sqlite database when user quits
  src/client.js
  src/plugins/sqlite.js
  test/plugins/sqlite.js
Labels: Type: Bug

#1860 Add advanced toggle and hide certain settings by default
  client/js/options.js
  client/views/windows/settings.tpl
Labels: Type: Feature

#2196 Remove `thelounge config` from the CLI
  src/command-line/config.js
  src/command-line/index.js
Labels: Type: Deprecation, Type: Feature

#2201 Remove `mailto:` part of security email address
  SECURITY.md
Labels: Type: Bug, Type: Documentation

#2194 Upgrade to Font Awesome 5
  client/css/style.css
  package.json
  test/tests/build.js
  webpack.config.js
  yarn.lock
Labels: Type: Feature

#2205 Fix join and part icons
  client/css/style.css
Labels: Type: Bug

#2185 Convert the entire viewport to use flexbox
  client/css/style.css
  client/index.html.tpl
  client/js/lounge.js
  client/js/slideout.js
  client/themes/example.css
Labels: Type: Feature

#2152 Insert channel/user into channel list at alphabetically sorted point, not just the end
  client/js/socket-events/join.js
  src/models/network.js
  src/plugins/inputs/query.js
  src/plugins/irc-events/banlist.js
  src/plugins/irc-events/join.js
  src/plugins/irc-events/list.js
  src/plugins/irc-events/message.js
  src/plugins/irc-events/whois.js
  test/models/network.js
Labels: Type: Feature

#2213 Do not repaint theme on page load
  client/js/options.js
Labels: Type: Bug

#2217 Fix some URLs not being sent as-is to the client
  src/plugins/irc-events/link.js
  test/plugins/link.js
Labels: Type: Bug

#2210 Use undate library to handle modifier keys
  client/js/keybinds.js
  package.json
  yarn.lock
Labels: Type: Feature

#2222 Do not try to write anything to sqlite after its closed
  src/plugins/sqlite.js
Labels: Type: Bug

#2212 Allow hiding channel list on desktop
  client/css/style.css
Labels: Type: Feature

#2199 Add logo to the sign in page
  client/css/style.css
  client/img/logo-vertical-transparent-bg-inverted.svg
  client/index.html.tpl
  client/themes/morning.css
  client/themes/zenburn.css
  client/views/windows/sign_in.tpl
Labels: Type: Feature

#2073 Enforce object literal shorthand syntax with ESLint
  .eslintrc.yml
  client/js/autocompletion.js
  client/js/constants.js
  client/js/keybinds.js
  client/js/libs/handlebars/ircmessageparser/merge.js
  client/js/localStorage.js
  client/js/lounge.js
  client/js/options.js
  client/js/renderPreview.js
  client/js/socket-events/auth.js
  client/js/socket.js
  client/js/sorting.js
  client/js/utils.js
  src/client.js
  src/clientManager.js
  src/identification.js
  src/models/chan.js
  src/plugins/inputs/connect.js
  src/plugins/irc-events/link.js
  src/plugins/packages/themes.js
  test/commands/mode.js
  test/models/chan.js
  test/util.js
Labels: Meta: Internal

#2237 Send hexip in ident responses
  src/plugins/irc-events/connection.js
Labels: Type: Bug

#2206 Add keybinds for cycling through networks/lobbies
  client/js/keybinds.js
  client/views/windows/help.tpl
Labels: Type: Feature

#2236 Rework how unread marker is moved when status messages are hidden
  client/js/socket-events/msg.js
Labels: Type: Bug

#2215 Do not aggressively focus input when clicking anywhere and handle typing out of focus
  client/js/keybinds.js
  client/js/lounge.js
  client/js/renderPreview.js
  client/js/utils.js
Labels: Type: Feature

#2241 Update express to 4.16.3
  package.json
  yarn.lock
Labels: greenkeeper

#2242 Keep input reference as jquery object
  client/js/keybinds.js
Labels: Type: Bug

#2225 Select lobby of network when collapsing network
  client/js/render.js
Labels: Type: Feature

#2235 Store visibility status of sidebar menus
  client/js/lounge.js
  client/js/socket-events/init.js
  client/js/utils.js
Labels: Type: Feature

#2247 Print failed login attempts to console
  src/server.js
Labels: Type: Security

#2246 Add a semi-opaque overlay when channel list is open on mobile
  client/css/style.css
  client/index.html.tpl
  client/js/lounge.js
  client/js/slideout.js
Labels: Type: Feature

#2195 Save collapsed state to localstorage
  client/js/render.js
  client/views/network.tpl
Labels: Type: Feature

#2186 Improve accessibility for emoji
  client/js/libs/fullnamemap.json
  client/js/libs/handlebars/parse.js
  scripts/generate-emoji.js
  test/client/js/libs/handlebars/parse.js
Labels: Type: Feature

#2221 Improve readability and styling of shortcut keys in the Help section
  client/css/style.css
  client/themes/morning.css
  client/themes/zenburn.css
  client/views/windows/help.tpl
Labels: Type: Documentation

#2251 Render video and audio previews only after canplay event fires
  client/js/renderPreview.js
Labels: Type: Bug

#2255 Fix typo in CTCP request
  client/views/actions/ctcp_request.tpl
Labels: Type: Bug, Type: Documentation

#2252 Fix `yarn coverage` script on Windows
  package.json
  test/.nycrc-mocha-webpack
Labels: Meta: Internal, Type: Bug

#2263 Bind formatting hotkeys on input element
  client/js/keybinds.js
Labels: Meta: Internal

#2262 stop propagation, prevent input history call when alt is involved
  client/js/keybinds.js
  client/js/libs/jquery/inputhistory.js
Labels: Type: Bug

#2259 Scroll channel list only when using keybinds
  client/js/keybinds.js
  client/js/lounge.js
Labels: Type: Bug

#2254 Empty local storage on sign out and move the sign out button to the settings
  client/css/style.css
  client/index.html.tpl
  client/js/auth.js
  client/js/localStorage.js
  client/js/location.js
  client/js/lounge.js
  client/js/socket-events/sessions_list.js
  client/js/socket-events/sign_out.js
  client/themes/crypto.css
  client/views/session.tpl
  package.json
  src/log.js
  test/client/js/authTest.js
  test/plugins/packages/indexTest.js
  test/src/command-line/utilsTest.js
  test/util.js
  yarn.lock
Labels: Type: Bug, Type: Security

#2268 Do not condense actions that are performed or related to the user
  client/js/render.js
Labels: Type: Feature

#2273 Fix order in oidentd file
  src/identification.js
Labels: Type: Bug

#2274 Create issue template
  ISSUE_TEMPLATE.md
Labels: Type: Documentation

#2258 Unfocus input on touch devices to close the keyboard
  client/js/lounge.js
Labels: Type: Bug

#2275 Autocomplete bracket and quote characters like in a modern IDE
  client/js/keybinds.js
Labels: Type: Feature

#2284 Hide autocompletion menu when input is submitted
  client/js/autocompletion.js
Labels: Type: Bug

#2285 quote-props: consistent-as-needed
  .eslintrc.yml
  client/js/keybinds.js
  src/plugins/changelog.js
Labels: Meta: Internal

#2287 Send `Accept` header when fetching links
  src/plugins/irc-events/link.js
  test/plugins/link.js
Labels: Type: Bug

#2282 Reduce lightness of low contrast nick colors to reach AA level of WCAG 2.0
  client/css/style.css
  client/themes/zenburn.css
Labels: Type: Feature

#2292 Fix lint issue on master; increase timeout globally on CI
  src/plugins/irc-events/link.js
  test/plugins/sqlite.js
Labels: Meta: Internal

#2296 Exclude Node v9.9 from Travis build, for now
  .travis.yml
Labels: Meta: Internal, Type: Bug

#2297 Fix/Improve some nick fallbacks
  src/client.js
  src/plugins/irc-events/error.js
Labels: Type: Bug

#2298 Do not close sidebar when collapsing networks
  client/js/lounge.js
  client/js/render.js
Labels: Type: Bug

#2286 Reimplement input history
  client/js/keybinds.js
  client/js/libs/jquery/inputhistory.js
  client/js/lounge.js
Labels: Meta: Internal

#2305 Fix bug preventing to click on channels/queries
  client/js/lounge.js
Labels: Type: Bug

#2303 catch stderr from yarn subprocess, addresses #2301
  src/command-line/install.js
  src/command-line/uninstall.js
Labels: Type: Bug

#1878 Pull context menu code out of lounge.js and make it more generic
  client/js/contextMenu.js
  client/js/contextMenuFactory.js
  client/js/lounge.js
Labels: Meta: Internal, Type: Feature

#2289 Add auto-prepend behaviour for unprefixed channel names
  client/js/lounge.js
Labels: Type: Feature

#2270 Replace pseudo element gradient fade with mask-image
  client/css/style.css
  client/themes/crypto.css
  client/themes/morning.css
  client/themes/zenburn.css
Labels: Meta: Internal

#2309 Remove left padding from sidebar in example theme
  client/themes/example.css
Labels: Type: Bug

#2312 Re-include latest Node.js v9 version in Travis build
  .travis.yml
Labels: Type: Bug

#2314 Fix autocomplete selection when hitting Enter
  client/js/keybinds.js
Labels: Type: Bug

#2290 Add ?channels=x,y,z alias for ?join=x,y,z
  client/js/lounge.js
Labels: Type: Feature
