Repository thelounge/thelounge, pull requests merged in 2018-05, with the labels that each got.

#2396 Use per-client channel and message ids
  src/client.js
  src/models/chan.js
  src/models/msg.js
  src/plugins/inputs/query.js
  src/plugins/irc-events/banlist.js
  src/plugins/irc-events/chghost.js
  src/plugins/irc-events/join.js
  src/plugins/irc-events/list.js
  src/plugins/irc-events/message.js
  src/plugins/irc-events/nick.js
  src/plugins/irc-events/whois.js
  src/plugins/sqlite.js
  test/models/chan.js
  test/plugins/sqlite.js
Labels: Meta: Internal

#2406 Fix channel and ban lists in context menu not working
  client/js/contextMenuFactory.js
Labels: Type: Bug

#2404 Fix join channel ui moving when sorting channels
  client/js/socket-events/sync_sort.js
Labels: Type: Bug

#2409 Fix CSS issues in Microsoft Edge
  client/css/style.css
Labels: Type: Bug

#2408 Minor optimization in style parser
  client/js/libs/handlebars/ircmessageparser/merge.js
  client/js/libs/handlebars/parse.js
  test/client/js/libs/handlebars/ircmessageparser/merge.js
Labels: Meta: Internal

#2405 Show a ghost placeholder when dragging channels
  client/css/style.css
Labels: Type: Feature

#2420 Use new fontawesome package
  package.json
  webpack.config.js
  yarn.lock
Labels: greenkeeper

#2428 Fix merge() in parser not filling unstyled text correctly
  client/js/libs/handlebars/ircmessageparser/merge.js
  test/client/js/libs/handlebars/ircmessageparser/merge.js
Labels: Type: Bug

#2378 Add prefix to channels from connect window
  client/js/lounge.js
  client/js/socket-events/configuration.js
  client/js/socket-events/init.js
  src/client.js
Labels: Type: Bug

#2391 Gracefully fail if sqlite3 module fails to load
  src/plugins/sqlite.js
Labels: Type: Bug

#2414 Fix join channel form not working
  client/js/join-channel.js
  client/js/lounge.js
  client/js/render.js
  client/views/chan.tpl
  client/views/join_channel.tpl
Labels: Type: Bug

#2445 Pointer cursor hovering nicks in userlist
  client/css/style.css
Labels: Type: Bug

#2466 Update Travis and Renovate configs
  .travis.yml
  renovate.json
Labels: Meta: Internal

#2397 Switch to `linkify-it` for url detection in messages
  client/js/libs/handlebars/ircmessageparser/findLinks.js
  package.json
  src/plugins/irc-events/link.js
  test/client/js/libs/handlebars/ircmessageparser/findLinks.js
  test/client/js/libs/handlebars/parse.js
  test/plugins/link.js
  yarn.lock
Labels: Type: Feature

#2366 Refactor userLog to be the same as sqlite logger
  package.json
  src/client.js
  src/helper.js
  src/models/chan.js
  src/models/network.js
  src/plugins/messageStorage/sqlite.js
  src/plugins/messageStorage/text.js
  src/userLog.js
  test/plugins/sqlite.js
  yarn.lock
Labels: Meta: Internal

#2471 Remove URIjs
  client/js/socket-events/configuration.js
  package.json
  yarn.lock
Labels: Meta: Internal

#2197 Add support for /ignore, /unignore and /ignorelist commands
  client/css/style.css
  client/js/constants.js
  client/js/contextMenuFactory.js
  client/js/socket-events/msg.js
  client/views/actions/ignore_list.tpl
  client/views/windows/help.tpl
  src/client.js
  src/helper.js
  src/models/msg.js
  src/models/network.js
  src/plugins/inputs/ignore.js
  src/plugins/irc-events/message.js
  test/models/network.js
  test/tests/hostmask.js
Labels: Type: Feature

#2429 Add password visibility toggle feature
  client/css/bootstrap.css
  client/css/style.css
  client/js/socket-events/auth.js
  client/js/socket-events/configuration.js
  client/js/socket-events/network.js
  client/js/utils.js
  client/views/reveal-password.tpl
  client/views/windows/connect.tpl
  client/views/windows/settings.tpl
  client/views/windows/sign_in.tpl
Labels: Type: Feature

#2480 Show connect window when last network is removed
  client/js/render.js
  client/js/socket-events/quit.js
Labels: Type: Bug

#2487 Fix mouse cursor on userlist
  client/css/style.css
Labels: Meta: Internal
