Repository thelounge/thelounge, pull requests merged in 2018-10, with the labels that each got.

#2824 Fix stored image previews not being dereferenced
  src/models/chan.js
Labels: Type: Bug

#2828 Put unread and highlight counts in aria-label in the channel list
  client/views/chan.tpl
Labels: Type: Bug

#2840 Bring back aria-label to fix broken code
  client/views/chan.tpl
Labels: Type: Bug

#2848 Make sure registered command is actually a function
  src/client.js
Labels: Type: Bug

#2849 Use hasOwnProperty when checking for webirc
  src/models/network.js
Labels: Type: Bug

#2851 Force express server to run in production mode
  src/plugins/uploader.js
  src/server.js
Labels: Type: Bug

#2854 Fix touch position being null when touching with multiple fingers
  client/js/slideout.js
Labels: Type: Bug

#2858 Hard limit nicks to 100 characters, add maxlength on connect inputs
  client/views/windows/connect.tpl
  src/models/network.js
  src/plugins/inputs/nick.js
Labels: Type: Bug

#2859 Fix timing issue crashing on undefined when setting openChannel
  src/client.js
  src/server.js
Labels: Type: Bug

#2871 Update semver and lock file
  package.json
  yarn.lock
Labels: Type: Dependencies

#2876 Generate new secure entries for Travis deploy step to npm
  .travis.yml
Labels: Meta: Internal

#2877 Add Node.js v11 to the Travis CI matrix
  .travis.yml
Labels: Meta: Internal

#2881 Fix config generator script comment 🙄
  scripts/generate-config-doc.js
Labels: Meta: Internal

#2883 Sanitize logo url in readme
  README.md
Labels: Type: Bug, Type: Documentation

#2882 Minor fixes in the config
  defaults/config.js
  scripts/generate-config-doc.js
Labels: Type: Documentation
