Repository thelounge/thelounge, pull requests merged in 2019-11, with the labels that each got.

#3486 Disable copy hack in Firefox
  client/js/clipboard.js
Labels: Type: Bug

#3485 Allow configuring base url for uploads
  defaults/config.js
  src/helper.js
  src/plugins/uploader.js
Labels: Type: Feature

#3483 Improvements to network connections on startup
  src/client.js
  test/tests/customhighlights.js
Labels: Meta: Internal

#3482 Load existing users on startup when LDAP is enabled
  src/clientManager.js
  test/models/network.js
  test/plugins/auth/ldap.js
  test/plugins/storage.js
  test/server.js
Labels: Type: Bug

#3449 Use postcss to optimize css
  .browserslistrc
  .npmignore
  .stylelintrc.yml
  client/css/style.css
  client/themes/morning.css
  package.json
  postcss.config.js
  webpack.config.js
  yarn.lock
Labels: Meta: Internal

#3493 Import primer-tooltips css
  client/css/style.css
  client/index.html.tpl
  test/tests/build.js
  webpack.config.js
Labels: Meta: Internal

#3498 Print package versions on startup
  src/plugins/packages/index.js
  test/fixtures/.thelounge/packages/node_modules/thelounge-package-foo/package.json
  test/plugins/packages/indexTest.js
Labels: Meta: Internal

#2821 Add file size to link preview
  client/components/LinkPreviewFileSize.vue
  client/css/style.css
  client/js/constants.js
  client/js/libs/handlebars/parse.js
  src/plugins/irc-events/link.js
  test/client/js/libs/handlebars/parse.js
  test/plugins/link.js
Labels: Type: Feature

#3502 Add webpack hot module reloading for development
  README.md
  package.json
  src/command-line/start.js
  src/plugins/dev-server.js
  src/server.js
  webpack.config.js
  yarn.lock
Labels: Meta: Internal

#3490 Fix potential issue of history not loading when `showInActive` is the first message
  client/components/MessageList.vue
  client/js/socket-events/msg.js
  src/models/chan.js
Labels: Type: Bug

#3489 Enable some user commands for LDAP
  src/command-line/index.js
  src/command-line/users/index.js
Labels: Type: Feature

#3530 Bump cheerio to latest version
  package.json
  yarn.lock
Labels: Type: Dependencies

#3531 Ignore unknown settings
  client/js/store-settings.js
Labels: Type: Bug

#3532 Remove transition from context menu items
  client/css/style.css
Labels: Meta: Internal

#3521 Create release github action workflow
  .github/workflows/release.yml
  .travis.yml
  README.md
Labels: Meta: Internal

#3533 Show which channels have drafts in the network list
  client/components/ChannelWrapper.vue
  client/css/style.css
Labels: Type: Feature

#3535 Fix keybinds when chat input is focused.
  client/components/ChatInput.vue
Labels: Type: Bug

#3536 Do not compute filteredUsers if there's no search input
  client/components/ChatUserList.vue
Labels: Type: Bug

#3537 Fix spacing in kick reason
  client/components/MessageTypes/kick.vue
Labels: Type: Bug

#3538 Increase test timeout due to unpredictable I/O on CI services
  test/plugins/auth/ldap.js
  test/plugins/link.js
  test/plugins/sqlite.js
  test/plugins/storage.js
  test/server.js
Labels: Meta: Internal

#3434 Remove \uFE0F emoji variant from emoji name map
  client/js/helpers/fullnamemap.json
  client/js/helpers/parse.js
  scripts/generate-emoji.js
  test/client/js/helpers/parse.js
Labels: Meta: Internal
