Repository thelounge/thelounge, pull requests merged in 2019-05, with the labels that each got.

#3138 Move query to msg, fix #3049
  src/client.js
  src/plugins/inputs/msg.js
  src/plugins/inputs/query.js
Labels: Type: Bug

#2761 Add server config api
  src/plugins/packages/index.js
Labels: Type: Feature

#3179 Replace `request` with `got`
  package.json
  scripts/generate-emoji.js
  src/plugins/changelog.js
  src/plugins/irc-events/link.js
  src/server.js
  test/server.js
  yarn.lock
Labels: Meta: Internal

#3217 Remove incorrect lowest node version from readme
  README.md
Labels: Type: Documentation

#3218 Disable touch tooltip on "jump to recent messages" button
  client/components/Chat.vue
Labels: Type: Bug

#3226 Add paste file functionality
  client/js/upload.js
Labels: Type: Feature

#3236 Change upload abort error message
  client/js/upload.js
Labels: Meta: Internal

#3235 Print a warning when running as root
  src/command-line/index.js
Labels: Type: Documentation

#3237 Remove bogus prefetch limit
  src/plugins/irc-events/link.js
Labels: Type: Bug
