Repository thelounge/thelounge, pull requests merged in 2019-10, with the labels that each got.

#3432 Add public files for plugins
  src/plugins/packages/index.js
  src/server.js
Labels: Type: Feature

#3435 Key condensed messages by first message in array
  client/components/MessageList.vue
Labels: Type: Bug

#3437 Allow tab completion in middle of input
  client/js/autocompletion.js
Labels: Type: Bug

#3416 Set correct file owner for created user files and warn about it
  src/clientManager.js
  src/command-line/index.js
Labels: Type: Feature

#3436 Let OS generate a port in link prefetch tests
  test/plugins/link.js
  test/plugins/storage.js
Labels: Meta: Internal

#3438 Prefix channel before join
  client/components/JoinChannel.vue
  client/js/commands/join.js
Labels: Type: Feature

#3463 Remove Windows/OSX builds from Travis
  .travis.yml
Labels: Meta: Internal

#3462 Update badges in readme
  README.md
Labels: Type: Documentation

#3465 Bump ecmaVersion to 2018
  .eslintrc.yml
Labels: Meta: Internal

#3453 Synchronize user list correctly on reconnection
  client/js/socket-events/init.js
Labels: Type: Bug

#3460 Fix history not loading in certain cases after reconnect
  client/components/MessageList.vue
  client/js/socket-events/init.js
  client/js/socket-events/more.js
  client/js/vue.js
  src/client.js
  src/models/chan.js
  test/models/chan.js
Labels: Type: Bug

#3451 Increase contrast of headers in windows
  client/css/style.css
  client/themes/morning.css
Labels: Type: Bug

#3458 Do not print "no packages" warning when opening help on client
  src/plugins/packages/index.js
Labels: Type: Bug

#3455 Extract updated packages from pull request body
  scripts/changelog.js
Labels: Meta: Internal

#3461 Synchronize open channel on client on reconnection
  client/js/socket-events/auth.js
  src/server.js
Labels: Type: Bug

#3467 Fix uploader being initialized more than once
  client/components/ChatInput.vue
  client/js/socket-events/configuration.js
  client/js/upload.js
Labels: Type: Bug

#3470 Do not crash on first run due to config.js not existing
  src/command-line/index.js
Labels: Type: Bug

#3473 Hide user loaded message in tests
  test/tests/customhighlights.js
Labels: Meta: Internal

#3475 Make badges a little more consistent with each other
  README.md
Labels: Type: Documentation

#3474 Add changelog entry for v3.3.0
  CHANGELOG.md
Labels: Meta: Skip Changelog

#3450 Create devDependencies update prs on weekends
  renovate.json
Labels: Meta: Internal

#3345 improve RTL text support
  client/components/ChatInput.vue
  client/components/LinkPreview.vue
  client/components/Message.vue
  client/css/style.css
  client/js/libs/handlebars/parse.js
  test/client/js/libs/handlebars/parse.js
Labels: Type: Feature
