Repository thelounge/thelounge, pull requests merged in 2019-06, with the labels that each got.

#3251 Use github's emoji data (support unicode 12)
  client/js/libs/fullnamemap.json
  client/js/libs/handlebars/parse.js
  client/js/libs/simplemap.json
  scripts/generate-emoji.js
  test/client/js/libs/handlebars/parse.js
Labels: Type: Feature

#3250 Add extra socket/server error event handlers
  src/identification.js
  src/server.js
Labels: Meta: Internal

#3258 Fix file uploading when lounge is proxied in a subfolder
  client/js/upload.js
Labels: Type: Bug

#3259 Only prepend text with 'Notice: ' if it's the nick it's from
  client/css/style.css
Labels: Type: Bug
