Repository thelounge/thelounge, pull requests merged in 2019-01, with the labels that each got.

#2970 List website contributors as well when generating changelog entries
  scripts/changelog.js
Labels: Type: Bug, Type: Documentation

#2967 Add fallback ip address for unix sockets
  src/server.js
Labels: Type: Bug

#2958 Don't fallback to `host` in identd server
  src/identification.js
Labels: Type: Bug

#2959 Relax identd checks to make it more compatible
  src/identification.js
Labels: Meta: Internal

#2975 Fix .active styles incorrectly applying to hovered users in userlist
  client/css/style.css
Labels: Type: Bug

#2937 Empty storage directory after destroying all channels
  src/server.js
Labels: Type: Bug

#2977 Add an extra check for setting names
  src/server.js
Labels: Type: Bug

#2980 Fix highlight styles not applying to notices and actions
  client/css/style.css
  client/themes/morning.css
Labels: Type: Bug

#2983 Fix casing of "Upload file" tooltip
  client/index.html.tpl
Labels: Type: Feature

#2984 Make sure the changelog page is selectable, e.g. for copy-pasting commands
  client/css/style.css
Labels: Type: Bug, Type: Documentation

#2985 Fix incorrect use of fs.stat
  src/plugins/uploader.js
Labels: Type: Bug

#2998 Add changelog entry for v3.0.0
  CHANGELOG.md
  package.json
Labels: Meta: Skip Changelog, Type: Documentation

#2989 Always emit part message (required for logging)
  src/plugins/irc-events/part.js
Labels: Type: Bug

#2993 Use require.resolve for yarn
  src/command-line/utils.js
Labels: Meta: Internal

#2999 Keep using npm to clean up dist-tags after a stable release
  .travis.yml
Labels: Meta: Internal, Type: Bug

#2995 Fix line-height to match height in input
  client/css/style.css
Labels: Type: Bug

#3001 Update remaining dependencies and lock file
  package.json
  yarn.lock
Labels: Type: Dependencies

#3003 Bump Travis to use Node 10 LTS for Windows, OSX, and production builds
  .travis.yml
Labels: Meta: Internal

#2997 Do not report the (renamed) Renovate bot as a contributor
  scripts/changelog.js
Labels: Type: Bug, Type: Documentation

#3008 Add `webirc` key and commas to make it more understandable
  defaults/config.js
Labels: Type: Documentation
