Repository thelounge/thelounge, pull requests merged in 2019-12, with the labels that each got.

#3546 Fix sidebar not opening when lounge is open in a background tab
  client/components/App.vue
  client/js/vue.js
Labels: Type: Bug

#3549 Make client awayMessage a client setting
  client/components/Windows/Settings.vue
  client/js/settings.js
  src/client.js
  src/clientManager.js
  src/server.js
Labels: Type: Feature

#3548 Remove code that aided upgrade to v3
  src/command-line/index.js
  src/command-line/utils.js
  src/helper.js
  test/client/js/constantsTest.js
Labels: Meta: Internal

#3555 Apply user theme as soon as possible on page load
  client/js/loading-error-handlers.js
Labels: Type: Bug

#3539 Add Unicode 12.1 emojis
  client/js/helpers/fullnamemap.json
  client/js/helpers/simplemap.json
Labels: Type: Feature

#3561 Fix video element overflowing on chrome
  client/css/style.css
Labels: Type: Bug

#3553 Refactor some CSS styling
  client/components/App.vue
  client/components/ChannelWrapper.vue
  client/components/Chat.vue
  client/components/ChatInput.vue
  client/components/NetworkList.vue
  client/css/style.css
  client/js/keybinds.js
  client/js/vue.js
  client/themes/default.css
  client/themes/morning.css
Labels: Meta: Internal

#3566 Fix up css refactor
  client/components/NetworkList.vue
  client/css/style.css
Labels: Meta: Internal, Type: Bug

#3572 Remove unnecessary selectors
  client/css/style.css
Labels: Meta: Internal

#3571 Disable protocol register button if lockNetwork is enabled
  client/components/Windows/Settings.vue
Labels: Type: Feature

#3570 Allow empty parameter overrides
  client/components/Windows/Connect.vue
Labels: Type: Bug

#3578 Provide fake $HOME env to Yarn commands
  src/command-line/install.js
  src/command-line/upgrade.js
  src/command-line/utils.js
Labels: Type: Bug

#3579 Automatically load new packages (fs.watch package.json)
  src/command-line/index.js
  src/command-line/install.js
  src/plugins/packages/index.js
Labels: Type: Feature

#3577 Assign `preview.thumb` only after it is processed
  src/models/chan.js
  src/plugins/irc-events/link.js
Labels: Type: Bug

#3585 Fix link previews settings not being visible
  client/components/Windows/Settings.vue
Labels: Type: Bug

#3574 Remove bootstrap.css, use flexbox
  client/components/MessageList.vue
  client/components/NetworkForm.vue
  client/components/Session.vue
  client/components/Windows/Help.vue
  client/components/Windows/Settings.vue
  client/css/bootstrap.css
  client/css/style.css
  package.json
  yarn.lock
Labels: Meta: Internal

#3557 Fix "premature close" on link previews
  src/plugins/irc-events/link.js
Labels: Type: Bug

#3454 Automatically apply GitHub labels on issue creation
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
Labels: Type: Documentation

#3592 Round down image transform in image viewer to fix blurry images
  client/components/ImageViewer.vue
Labels: Type: Bug

#3591 Fix sign in being full width
  client/css/style.css
Labels: Type: Bug

#3590 Fix synchronizing settings on page load
  client/js/settings.js
  client/js/socket-events/configuration.js
  client/js/socket-events/init.js
  client/js/store-settings.js
Labels: Type: Bug

#3588 Hide awaymessage/highlights settings in public mode
  client/components/Windows/Settings.vue
Labels: Type: Bug

#3586 Use data-type attribute on .msg
  client/components/Message.vue
  client/components/MessageCondensed.vue
  client/css/style.css
  client/themes/morning.css
Labels: Meta: Internal

#3593 Fix keep nick setting nick to undefined on socket close
  src/plugins/irc-events/connection.js
Labels: Type: Bug

#3597 Fix format of IPv6 URI
  src/server.js
Labels: Type: Bug

#3599 Fix page and arrow keys not working correctly
  client/components/ContextMenu.vue
  client/js/keybinds.js
Labels: Type: Bug

#3600 Use Set() for condensed types
  client/components/MessageList.vue
  client/js/constants.js
  test/client/js/constantsTest.js
Labels: Meta: Internal

#3596 Use `friendlysize` helper consistently
  client/components/LinkPreviewFileSize.vue
  client/js/constants.js
  client/js/helpers/friendlysize.js
  test/client/js/helpers/friendlysizeTest.js
Labels: Type: Bug

#3604 Fix beforeunload not working
  client/js/socket-events/configuration.js
Labels: Type: Bug

#3589 Optimize user file updates
  src/client.js
  src/clientManager.js
  src/command-line/users/reset.js
  src/server.js
  test/tests/customhighlights.js
Labels: Type: Bug

#3608 Relocate not-secure and not-connected classes and make sure channel exists in jumpToChannel
  client/components/ChannelWrapper.vue
  client/components/NetworkList.vue
  client/css/style.css
  client/js/keybinds.js
Labels: Meta: Internal

#3606 Add preview for text/plain urls
  src/plugins/irc-events/link.js
  test/plugins/link.js
Labels: Type: Feature

#3602 Pretend to be facebook and twitter bots in link prefetcher
  src/plugins/irc-events/link.js
Labels: Meta: Internal

#3609 Remove querySelector in topic edit, fix save button style
  client/components/Chat.vue
  client/css/style.css
  client/js/helpers/contextMenu.js
Labels: Meta: Internal

#3534 Add `previous-source` class to messages with same sender
  client/components/Message.vue
  client/components/MessageList.vue
Labels: Type: Feature

#3603 Send 100 actual messages when requesting history with hidden or condensed status messages
  .npmignore
  client/components/App.vue
  client/components/Message.vue
  client/components/MessageCondensed.vue
  client/components/MessageList.vue
  client/js/autocompletion.js
  client/js/constants.js
  client/js/router.js
  client/js/socket-events/commands.js
  client/js/vue.js
  src/client.js
  test/client/js/constantsTest.js
Labels: Type: Feature

#3613 Don't show draft icon on lobbies.
  client/css/style.css
Labels: Type: Bug

#3614 Update status messages tooltip
  client/components/Windows/Settings.vue
Labels: Type: Bug

#3627 Create networks after setting user defaults
  src/client.js
Labels: Type: Bug

#3635 Set `-webkit-tap-highlight-color` to `transparent`
  client/css/style.css
Labels: Type: Bug

#3637 Lower node version to 10.15
  package.json
Labels: Meta: Internal

#3638 Replace control codes with a space
  client/js/helpers/ircmessageparser/parseStyle.js
  test/client/js/helpers/ircmessageparser/parseStyle.js
  test/client/js/helpers/parse.js
Labels: Type: Bug

#3633 Restrict image viewer bounds while moving
  client/components/ImageViewer.vue
Labels: Type: Bug

#3632 Check if there are any packages installed in upgrade command
  src/command-line/uninstall.js
  src/command-line/upgrade.js
  src/plugins/packages/index.js
Labels: Type: Bug

#3625 Add changelog for v4.0.0
  CHANGELOG.md
  yarn.lock
Labels: Meta: Skip Changelog

#3628 Collapse prefetch errors by default, and correctly track user toggle
  client/components/LinkPreview.vue
  src/plugins/irc-events/link.js
  test/plugins/link.js
Labels: Type: Bug
