Repository thelounge/thelounge, pull requests merged in 2019-02, with the labels that each got.

#3010 Fix incorrect 404 error for files with unknown file type
  src/plugins/uploader.js
Labels: Type: Bug

#3011 Fix up link insertion after uploads to be saner
  client/js/socket-events/uploads.js
Labels: Type: Bug

#3022 Make sure the editorconfig indent size applies to all file formats
  .editorconfig
Labels: Meta: Internal

#3031 Invites should not automatically highlight you.
  src/plugins/irc-events/invite.js
Labels: Type: Bug

#3034 Allow forcing /disconnect to stop reconnection timer from running
  src/plugins/inputs/disconnect.js
Labels: Type: Bug

#3033 Fix up textarea growing to avoid rounding issues in Chrome
  client/css/style.css
  client/js/lounge.js
Labels: Type: Bug

#3042 Add changelog entry for v3.0.1
  CHANGELOG.md
  package.json
Labels: Meta: Skip Changelog, Type: Documentation

#3044 Fix copying text in Firefox
  client/css/style.css
Labels: Type: Bug

#3045 Change build priority order in Travis
  .travis.yml
Labels: Meta: Internal

#3058 Downgrade webpack and regenerate lockfile
  package.json
  yarn.lock
Labels: Type: Dependencies

#3064 Fix casing of "Upload file" tooltip
  client/components/ChatInput.vue
Labels: Type: Bug

#3063 Improve scroll-down button UI
  client/components/Chat.vue
  client/css/style.css
Labels: Type: Bug

#3079 Put channel errors and unhandled numerics to relevant channel if it exists
  src/plugins/irc-events/error.js
  src/plugins/irc-events/unhandled.js
Labels: Type: Feature

#2974 Set scrollbar properties for Firefox 64+
  client/css/style.css
  client/themes/morning.css
Labels: Type: Feature

#3082 Display a broken link icon and red text color when not joined on a channel
  client/components/Channel.vue
  client/components/ChannelWrapper.vue
  client/css/style.css
Labels: Type: Feature

#3083 Move closing brackets on a new line in Vue files
  .eslintrc.yml
  client/components/App.vue
  client/components/Channel.vue
  client/components/ChannelWrapper.vue
  client/components/Chat.vue
  client/components/ChatInput.vue
  client/components/ChatUserList.vue
  client/components/DateMarker.vue
  client/components/JoinChannel.vue
  client/components/LinkPreview.vue
  client/components/LinkPreviewToggle.vue
  client/components/Message.vue
  client/components/MessageCondensed.vue
  client/components/MessageList.vue
  client/components/MessageTypes/away.vue
  client/components/MessageTypes/back.vue
  client/components/MessageTypes/invite.vue
  client/components/MessageTypes/kick.vue
  client/components/MessageTypes/motd.vue
  client/components/MessageTypes/part.vue
  client/components/MessageTypes/quit.vue
  client/components/MessageTypes/topic.vue
  client/components/MessageTypes/whois.vue
  client/components/NetworkList.vue
  client/components/NetworkLobby.vue
  client/components/Special/ListBans.vue
  client/components/Special/ListChannels.vue
  client/components/Special/ListIgnored.vue
  client/components/Username.vue
  client/components/UsernameFiltered.vue
  test/client/components/ParsedMessageTestWrapper.vue
Labels: Meta: Internal

#3088 Use Vue to show/hide insecure/disconnected icons instead of CSS
  client/components/Channel.vue
  client/components/NetworkLobby.vue
  client/css/style.css
Labels: Meta: Internal
