Repository thelounge/thelounge, pull requests merged in 2019-03, with the labels that each got.

#3100 Print a warning for invalid keys in config file or cli arguments
  src/command-line/index.js
  src/helper.js
Labels: Type: Feature

#3093 Fix (dis)connect icons in context menu being reverse of what they should be
  client/css/style.css
Labels: Type: Bug

#3108 Sanitize user and real names
  src/models/network.js
Labels: Type: Bug

#3123 Add support for /kill
  src/client.js
  src/plugins/inputs/kill.js
Labels: Type: Feature

#3116 Add aria-label on link preview toggle button
  client/components/LinkPreviewToggle.vue
Labels: Type: Bug

#3109 Display current channel mode on /mode command
  client/components/MessageTypes/mode_channel.vue
  client/css/style.css
  src/models/msg.js
  src/plugins/irc-events/mode.js
Labels: Type: Feature

#3107 Send SETNAME command if user edits realname field
  src/models/network.js
Labels: Type: Feature

#3125 Spelling fix for manual disconnect message
  src/client.js
Labels: Type: Bug, Type: Documentation

#3111 Use async/await in service worker, do not wait for cache for successful requests
  client/index.html.tpl
  client/service-worker.js
  src/helper.js
  src/server.js
  webpack.config.js
Labels: Meta: Internal

#3037 Re-implement file uploading with old school multipart forms
  client/components/ChatInput.vue
  client/css/style.css
  client/js/socket-events/index.js
  client/js/socket-events/uploads.js
  client/js/upload.js
  package.json
  src/plugins/uploader.js
  yarn.lock
Labels: Meta: Internal, Type: Feature

#3137 Force no-cache on service-worker and sourcemap files
  src/server.js
Labels: Type: Bug

#3136 Handle redirected requests correctly in service worker
  client/service-worker.js
Labels: Type: Bug

#3133 Hide unknown key warning in mergeConfig test
  test/tests/mergeConfig.js
Labels: Meta: Internal

#3150 Replace mocha-webpack with mochapack, and remove browser test setup that we never used
  package.json
  test/.nycrc-mochapack
  test/mochapack.opts
  webpack.config-browser.js
  yarn.lock
Labels: Meta: Internal
