Repository thelounge/thelounge, pull requests merged in 2019-07, with the labels that each got.

#2757 Add support for command plugins
  client/js/constants.js
  client/js/socket-events/commands.js
  client/js/socket-events/index.js
  src/client.js
  src/plugins/inputs/index.js
  src/plugins/packages/index.js
  src/server.js
  test/client/js/constantsTest.js
  test/plugins/inputs/indexTest.js
Labels: Type: Feature

#3276 Make sure unhandled command has params
  src/plugins/irc-events/unhandled.js
Labels: Type: Bug

#3279 Add a message about experimental API
  src/plugins/packages/index.js
  test/plugins/packages/indexTest.js
Labels: Type: Documentation

#3280 Change unable to load sqlite3 message
  src/plugins/messageStorage/sqlite.js
Labels: Type: Documentation

#3281 Refactor command API for plugins
  src/client.js
  src/plugins/inputs/index.js
  src/plugins/packages/index.js
  src/plugins/packages/publicClient.js
  src/server.js
Labels: Type: Feature

#3282 Changelog for v3.1.0
  CHANGELOG.md
Labels: Meta: Skip Changelog

#3292 Upgrade packages and the lock file
  package.json
  yarn.lock
Labels: Type: Dependencies

#3296 Correctly parse numbers when passed in CLI
  src/command-line/utils.js
  test/src/command-line/utilsTest.js
Labels: Type: Bug

#3294 Verify reverse DNS when looking up hostnames for webirc
  src/server.js
Labels: Type: Bug

#3299 Fix channel sorting to work across clients on Vue
  client/js/socket-events/sync_sort.js
Labels: Type: Bug

#3297 A better way of disabling sorting on touch devices
  client/components/NetworkList.vue
Labels: Type: Bug

#3060 Set up Prettier on HTML, JSON, Markdown, and YAML files
  .editorconfig
  .eslintrc.yml
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .prettierignore
  .prettierrc.yml
  CHANGELOG.md
  README.md
  client/thelounge.webmanifest
  package.json
  renovate.json
  scripts/changelog.js
  test/.nycrc-mocha
  test/.nycrc-mocha.json
  test/.nycrc-mochapack
  test/.nycrc-mochapack.json
  test/.nycrc-report.json
  test/client/index.html
  test/fixtures/.thelounge/vapid.json
  yarn.lock
Labels: Meta: Internal

#3305 Merge network/channel objects when reconnecting to keep object references
  client/js/lounge.js
  client/js/socket-events/init.js
Labels: Type: Bug

#3307 Store ip and language in a separate object in user file
  defaults/config.js
  src/client.js
  src/clientManager.js
  src/models/network.js
  src/plugins/irc-events/connection.js
  src/plugins/irc-events/link.js
  src/server.js
  test/models/network.js
  test/plugins/link.js
  test/util.js
Labels: Meta: Internal, Type: Bug

#2760 Add check for outdated packages, and show on the help screen.
  client/css/style.css
  client/js/socket-events/changelog.js
  client/views/version_checker.tpl
  src/command-line/index.js
  src/command-line/outdated.js
  src/plugins/packages/index.js
  src/server.js
Labels: Type: Feature

#1873 Add custom focus outlines for inputs and green buttons
  client/css/style.css
Labels: Type: Bug, help wanted

#3320 Fix channel list not working on some touch devices
  client/components/NetworkList.vue
Labels: Type: Bug
