Repository thelounge/thelounge, pull requests merged in 2019-08, with the labels that each got.

#3342 Disable io cookie
  src/server.js
Labels: Meta: Internal

#3339 Parse target group for sent messages when echo-message is not enabled
  src/plugins/inputs/msg.js
  src/plugins/inputs/notice.js
Labels: Type: Bug

#3343 Fix formatting hotkeys on non english locales
  client/components/ChatInput.vue
Labels: Type: Bug

#3335 Handle upload token requesting in a better way
  client/js/upload.js
Labels: Type: Bug

#3329 Send service worker fetch errors to client
  client/js/loading-error-handlers.js
  client/service-worker.js
Labels: Type: Feature

#3326 Allow themes to change theme-color
  client/js/options.js
  client/js/socket-events/configuration.js
  client/views/windows/settings.tpl
  src/plugins/packages/themes.js
  src/server.js
Labels: Type: Feature

#3352 Make /raw actually write to network as-is
  src/plugins/inputs/raw.js
Labels: Type: Bug

#3347 Open list channel on data updates
  client/js/socket-events/msg_special.js
Labels: Type: Bug

#3359 Add keybind for cycling to the next unread window
  client/js/keybinds.js
  client/views/windows/help.tpl
Labels: Type: Feature

#3349 Add functionality to edit channel topic from the user interface
  client/components/Chat.vue
  client/css/style.css
  client/js/contextMenuFactory.js
  client/js/vue.js
Labels: Type: Feature

#3361 Display an error on unknown command
  src/command-line/index.js
Labels: Type: Bug

#3366 Adds data-current-channel to #chat-container
  client/components/Chat.vue
Labels: Meta: Internal

#3382 Some fixes in file uploading
  client/js/upload.js
  src/plugins/uploader.js
Labels: Meta: Internal
