Repository thelounge/thelounge, pull requests merged in 2020-07, with the labels that each got.

#3918 Make usernames case-insensitive when logging in
  src/clientManager.js
  src/server.js
Labels: Type: Feature

#3845 Implement native app badges for highlights (Chrome 81+)
  client/js/vue.js
Labels: Type: Feature

#3978 Fix date marker not displaying sometimes
  client/components/MessageList.vue
Labels: Type: Bug

#3976 Test node v14
  .github/workflows/build.yml
Labels: Meta: Internal

#3977 Allow changing network name in private mode with lockNetwork
  client/components/NetworkForm.vue
  src/models/network.js
Labels: Type: Bug

#3981 Change wording of prefetchStorage option
  defaults/config.js
Labels: Type: Documentation

#3993 Improvements to mentions window
  client/components/Mentions.vue
  src/server.js
Labels: Type: Feature

#3995 Cleanup vue router route guards
  client/js/router.js
  client/js/socket-events/init.js
Labels: Meta: Internal

#3986 Fix upload tokens expiring while uploading when TL is proxied
  client/js/upload.js
  src/plugins/uploader.js
Labels: Type: Bug

#3987 Refresh notification permission state when push is enabled
  client/js/webpush.js
Labels: Type: Bug

#3999 Fix layout trashing in Chrome causing typing lag
  client/css/style.css
Labels: Meta: Internal

#3983 Add option to disable media preview.
  defaults/config.js
  src/plugins/irc-events/link.js
  test/plugins/link.js
Labels: Type: Feature

#4003 Add break-word on mentions popup content
  client/components/Mentions.vue
Labels: Type: Bug

#4005 Fix mode message only making last nick clickable
  src/plugins/irc-events/mode.js
Labels: Type: Bug
