Repository thelounge/thelounge, pull requests merged in 2020-02, with the labels that each got.

#3711 Use hostname from notice if available
  src/plugins/irc-events/message.js
Labels: Meta: Internal

#3730 Small fixes to user list search
  client/components/ContextMenu.vue
  client/components/Username.vue
  client/css/style.css
Labels: Meta: Internal

#3735 Add emojis 13.0
  client/js/helpers/fullnamemap.json
  client/js/helpers/simplemap.json
Labels: Type: Feature

#3752 Fix increasing test timeout on github actions
  test/plugins/auth/ldap.js
  test/plugins/link.js
  test/plugins/sqlite.js
  test/plugins/storage.js
  test/server.js
  test/util.js
Labels: Meta: Internal

#3744 Add icon purpose in webmanifest
  client/thelounge.webmanifest
Labels: Meta: Internal

#3712 Add support for webirc secure option
  src/models/network.js
Labels: Meta: Internal

#3594 Jump to channel switcher
  client/components/App.vue
  client/components/Channel.vue
  client/components/ChannelWrapper.vue
  client/components/NetworkList.vue
  client/components/NetworkLobby.vue
  client/components/Windows/Help.vue
  client/css/style.css
  client/js/vue.js
Labels: Type: Feature

#3753 Wrap stdout parsing from yarn into try/catch
  src/command-line/utils.js
Labels: Type: Bug

#3765 Fix incorrectly updating unread counter for 'show in active' messages
  client/js/socket-events/msg.js
Labels: Type: Bug

#3781 Improve wav audio detection
  src/plugins/irc-events/link.js
  src/plugins/uploader.js
Labels: Type: Bug

#3770 Implement strict transport security (STS) for IRC networks
  client/components/NetworkForm.vue
  src/client.js
  src/models/network.js
  src/plugins/inputs/disconnect.js
  src/plugins/inputs/quit.js
  src/plugins/irc-events/cap.js
  src/plugins/sts.js
Labels: Type: Feature, Type: Security

#3767 Unprefix setname cap
  src/models/network.js
Labels: Meta: Internal

#3762 Change sqlite parallelize to serialize when loading messages
  src/plugins/messageStorage/sqlite.js
Labels: Meta: Internal

#3741 Write prettier error messages for certain errors
  client/components/MessageTypes/error.vue
  src/plugins/irc-events/error.js
Labels: Type: Feature

#3783 Fix not being able to uninstall packages
  src/command-line/uninstall.js
Labels: Type: Bug
