Repository thelounge/thelounge, pull requests merged in 2020-03, with the labels that each got.

#3793 Add maskable purpose & removes monochrome
  client/thelounge.webmanifest
Labels: Meta: Internal

#3789 Fix sending unhandled numerics to target channel
  src/plugins/irc-events/unhandled.js
Labels: Type: Bug

#3790 Add role=group to status messages setting
  client/components/Windows/Settings.vue
Labels: Type: Feature

#3787 Add an option to display 12h times
  client/components/Chat.vue
  client/components/Message.vue
  client/components/Windows/Settings.vue
  client/css/style.css
  client/js/constants.js
  client/js/settings.js
Labels: Type: Feature

#3778 Clear channel history (and a new confirmation dialog)
  client/components/App.vue
  client/components/ConfirmDialog.vue
  client/components/ContextMenu.vue
  client/css/style.css
  client/js/helpers/contextMenu.js
  client/js/socket-events/history_clear.js
  client/js/socket-events/index.js
  client/js/vue.js
  src/client.js
  src/plugins/messageStorage/sqlite.js
  src/plugins/messageStorage/text.js
  src/server.js
Labels: Type: Feature

#3799 Upgrade yarn.lock
  yarn.lock
Labels: Type: Dependencies

#3808 Fix up first argument not being used as part message
  src/plugins/inputs/part.js
Labels: Type: Bug

#3815 Add escape key description to help section
  client/components/Windows/Help.vue
Labels: Type: Documentation

#3816 Remove "The Lounge" from connect in public
  client/components/NetworkForm.vue
Labels: Meta: Internal

#3817 Separate active sessions section
  client/components/Session.vue
  client/components/Windows/Settings.vue
  client/css/style.css
  client/js/store.js
  src/server.js
Labels: Type: Feature

#3797 Pass in client manager object in update checker
  src/plugins/changelog.js
Labels: Type: Bug

#3814 Do not handle navigation keybinds in inputs if not empty
  client/components/App.vue
  client/components/NetworkList.vue
  client/js/helpers/isIgnoredKeybind.js
  client/js/keybinds.js
Labels: Type: Bug

#3810 Replace all uses of `fs-extra` with native methods
  package.json
  src/command-line/index.js
  src/command-line/start.js
  src/plugins/messageStorage/sqlite.js
  src/plugins/messageStorage/text.js
  src/plugins/storage.js
  src/plugins/uploader.js
  test/plugins/sqlite.js
  test/plugins/storage.js
  yarn.lock
Labels: Meta: Internal

#3828 Fix body overscroll and overflow on iOS Safari
  client/css/style.css
Labels: Type: Bug
