Repository thelounge/thelounge, pull requests merged in 2020-08, with the labels that each got.

#4014 Disable link prefetching for urls with no schema specified
  client/js/helpers/ircmessageparser/findLinks.js
  client/js/helpers/parse.js
  src/plugins/irc-events/link.js
  test/client/js/helpers/ircmessageparser/findLinks.js
  test/plugins/link.js
Labels: Type: Feature

#4020 Use lodash where possible
  client/js/store-settings.js
  src/client.js
  src/server.js
Labels: Meta: Internal

#4028 Disable settings sync for browser notifications and notification sound
  client/js/settings.js
Labels: Type: Feature

#4029 Replace dashes to underscores in emoji autocompletion
  client/js/helpers/simplemap.json
  scripts/generate-emoji.js
Labels: Meta: Internal

#4032 Increase unread counter for HELP and INFO messages
  src/plugins/irc-events/help.js
  src/plugins/irc-events/info.js
Labels: Type: Bug

#4038 Sync changed network name to open clients
  client/js/socket-events/network.js
  src/models/network.js
  test/models/network.js
Labels: Type: Bug

#4037 Remove `graphql-request` dependency from changelog script
  package.json
  scripts/changelog.js
  yarn.lock
Labels: Meta: Internal

#3998 Highlight exceptions
  client/components/Windows/Settings.vue
  client/js/settings.js
  src/client.js
  src/plugins/irc-events/link.js
  src/plugins/irc-events/message.js
  src/server.js
  test/plugins/link.js
  test/plugins/storage.js
  test/tests/customhighlights.js
Labels: Type: Feature

#4040 Skip video/audio embeds if og:type exists but does not specify it
  src/plugins/irc-events/link.js
Labels: Type: Feature

#4041 Add version support for packages.
  src/command-line/install.js
  src/helper.js
  src/plugins/packages/index.js
Labels: Type: Feature

#4042 Add .vscode settings and suggested extensions
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
Labels: Meta: Internal

#4055 Add enterkeyhint on chat input and topic save
  client/components/Chat.vue
  client/components/ChatInput.vue
Labels: Type: Feature
