Repository thelounge/thelounge, pull requests merged in 2020-04, with the labels that each got.

#3764 Render images in canvas before upload to remove exif
  client/components/Windows/Settings.vue
  client/js/settings.js
  client/js/upload.js
Labels: Type: Feature

#3856 Exclude node 10 on macOS from build matrix
  .github/workflows/build.yml
Labels: Meta: Internal

#3826 Upgrade to mocha@7 and remove mochapack
  package.json
  test/.mocharc.yml
  test/.nycrc-mochapack.json
  test/mocha.opts
  test/mochapack.opts
  webpack.config-test.js
  yarn.lock
Labels: Meta: Internal

#3858 Track mentions and add a window to view them
  client/components/App.vue
  client/components/Chat.vue
  client/components/Mentions.vue
  client/css/style.css
  client/js/socket-events/index.js
  client/js/socket-events/mentions.js
  client/js/store.js
  client/themes/morning.css
  src/client.js
  src/plugins/irc-events/message.js
  src/server.js
Labels: Type: Feature

#3857 Optimize user list updates for quit/part/kick events
  client/js/socket-events/msg.js
  src/plugins/irc-events/kick.js
  src/plugins/irc-events/part.js
  src/plugins/irc-events/quit.js
Labels: Meta: Internal

#3862 Render sidebar over the mentions popup on mobile
  client/components/Mentions.vue
Labels: Type: Bug

#3798 Implement navigation in image viewer
  client/components/ImageViewer.vue
  client/components/LinkPreview.vue
  client/components/Message.vue
Labels: Type: Feature

#3861 Move mentions loading text out of header
  client/components/Mentions.vue
Labels: Meta: Internal

#3864 Remove intersection-observer polyfill
  client/components/MessageList.vue
  package.json
  yarn.lock
Labels: Meta: Internal

#3867 Fix off-by-one color error in webmanifest
  client/index.html.tpl
  client/thelounge.webmanifest
Labels: Type: Bug

#3844 CertFP support; separate SASL configuration
  client/components/NetworkForm.vue
  client/components/Windows/Connect.vue
  client/components/Windows/Settings.vue
  client/css/style.css
  defaults/config.js
  package.json
  src/client.js
  src/helper.js
  src/models/network.js
  src/plugins/clientCertificate.js
  src/plugins/inputs/quit.js
  src/server.js
  test/fixtures/.gitignore
  test/models/network.js
  test/plugins/clientCertificate.js
  test/server.js
  yarn.lock
Labels: Type: Feature

#3870 Safeguard nick randomizer up to allowed length
  src/plugins/irc-events/error.js
Labels: Meta: Internal

#3871 Filter user loading at startup for "advanced" LDAP
  src/clientManager.js
  src/plugins/auth.js
  src/plugins/auth/ldap.js
  src/plugins/auth/local.js
  src/server.js
Labels: Type: Feature

#3868 Some fixes in mentions window
  client/components/Mentions.vue
  src/server.js
Labels: Type: Bug

#3875 Add an indicator to statusmsg messages
  client/components/Message.vue
  client/css/style.css
  src/plugins/irc-events/message.js
Labels: Type: Feature

#3872 Replace vue events with our own event bus
  client/components/App.vue
  client/components/ChannelWrapper.vue
  client/components/Chat.vue
  client/components/ChatInput.vue
  client/components/ConfirmDialog.vue
  client/components/ContextMenu.vue
  client/components/DateMarker.vue
  client/components/ImageViewer.vue
  client/components/LinkPreview.vue
  client/components/Mentions.vue
  client/components/MessageList.vue
  client/components/Username.vue
  client/js/eventbus.js
  client/js/helpers/contextMenu.js
  client/js/vue.js
Labels: Meta: Internal

#3885 Support multiple arguments in eventbus emit
  client/js/eventbus.js
Labels: Type: Bug

#3888 Fix msg id order when loading from sqlite
  src/plugins/messageStorage/sqlite.js
Labels: Type: Bug

#3889 Changes required for vue 3
  .eslintrc.yml
  client/components/Chat.vue
  client/components/Message.vue
  client/components/MessageList.vue
  client/components/NetworkList.vue
Labels: Meta: Internal
