Repository thelounge/thelounge, pull requests merged in 2021-11, with the labels that each got.

#4340 Improve responsiveness of channel name and topic.
  client/components/Chat.vue
  client/css/style.css
Labels: Type: Feature

#4351 Allow wildcards in hostmask
  src/helper.js
  test/tests/hostmask.js
Labels: Type: Feature

#4356 Bump required node version to 12.x and add 16.x builds
  .github/workflows/build.yml
  package.json
Labels: Type: Security

#4364 Allow escape key to close search bar and search page
  client/components/MessageSearchForm.vue
  client/components/Windows/SearchResults.vue
Labels: Type: Bug

#4368 Switch to thelounge/Sortable fork for Sortable.js
  package.json
  yarn.lock
Labels: Meta: Internal
