Repository thelounge/thelounge, pull requests merged in 2021-12, with the labels that each got.

#4361 Add /kickban
  client/components/Windows/Help.vue
  src/plugins/inputs/ban.js
Labels: Type: Feature

#4426 getGitCommit: allow git worktrees
  src/helper.js
Labels: Type: Bug

#4434 Remove uses of window.event.
  .eslintrc.yml
  client/components/Chat.vue
  client/components/InlineChannel.vue
  client/components/NetworkList.vue
  client/js/helpers/listenForTwoFingerSwipes.js
Labels: Meta: Internal

#4435 upload: improve error message
  client/js/upload.js
Labels: Type: Feature
