Repository thelounge/thelounge, pull requests merged in 2022-02, with the labels that each got.

#4459 Adding 'to' in a sentence in config.js
  defaults/config.js
Labels: Type: Documentation

#4463 update caniuse-lite
  yarn.lock
Labels: Type: Dependencies

#4462 clientCert: fix up error message
  src/plugins/clientCertificate.js
Labels: Type: Bug

#4467 README: suggest running 'yarn format:prettier' when linting fails
  README.md
Labels: Type: Documentation

#4453 Bump most deps
  .eslintrc.yml
  .stylelintrc.yml
  client/css/fontawesome.css
  client/css/style.css
  client/js/helpers/ircmessageparser/cleanIrcMessage.js
  client/themes/default.css
  client/themes/morning.css
  package.json
  scripts/changelog.js
  src/client.js
  src/plugins/inputs/msg.js
  src/plugins/irc-events/connection.js
  src/server.js
  test/client/js/helpers/ircmessageparser/anyIntersection.js
  test/client/js/helpers/ircmessageparser/findChannels.js
  test/client/js/helpers/parse.js
  test/plugins/link.js
  test/plugins/sqlite.js
  test/src/command-line/utilsTest.js
  webpack.config.js
  yarn.lock
Labels: Type: Dependencies

#4282 Add the option to mute channels, queries, and networks
  client/components/Channel.vue
  client/components/ChannelWrapper.vue
  client/components/Mentions.vue
  client/components/Windows/Help.vue
  client/css/style.css
  client/js/helpers/contextMenu.js
  client/js/socket-events/index.js
  client/js/socket-events/msg.js
  client/js/socket-events/mute_changed.js
  client/js/store.js
  src/client.js
  src/models/chan.js
  src/models/network.js
  src/plugins/inputs/index.js
  src/plugins/inputs/mute.js
  src/plugins/irc-events/message.js
  src/server.js
  test/models/chan.js
  test/models/network.js
Labels: Type: Feature

#4470 uploader.js: upload m4a as audio/mp4 | link.js: embed audio/mp4, x-flac, and x-m4a
  src/plugins/irc-events/link.js
  src/plugins/uploader.js
Labels: Type: Feature

#4473 Include leading '<' + remove leading ' ' when copying messages
  client/components/Message.vue
  client/css/style.css
Labels: Type: Bug

#4476 Show a nicer error in Chan.loadMessages() when network is misconfigured
  src/models/chan.js
Labels: Type: Bug

#4488 Fix /collapse from interacting with the server in public mode
  client/js/commands/collapse.js
  client/js/commands/expand.js
  src/server.js
Labels: Type: Bug

#4492 Re-add missing space between timestamp and nick
  client/components/Message.vue
Labels: Type: Bug
