Repository thelounge/thelounge, pull requests merged in 2022-08, with the labels that each got.

#4598 Fix regex escape for prefix patterns
  client/js/helpers/ircmessageparser/findChannels.ts
  test/client/js/helpers/ircmessageparser/findChannels.ts
Labels: Type: Bug

#4609 install: Document file: prefix in cli help
  server/command-line/install.ts
Labels: Type: Feature

#4610 install: expand ~ for local paths
  server/command-line/install.ts
Labels: Type: Feature

#4619 Added client type checking to webpack
  client/js/helpers/collapseNetwork.ts
  client/js/helpers/contextMenu.ts
  client/js/helpers/parseIrcUri.ts
  client/js/store.ts
  client/tsconfig.json
  package.json
  server/plugins/changelog.ts
  webpack.config.ts
  yarn.lock
Labels: Meta: Internal, Status: changes-requested

#4542 Use nick as a realname fallback
  defaults/config.js
  server/models/network.ts
  test/models/network.ts
Labels: Type: Feature
