Repository thelounge/thelounge, pull requests merged in 2022-04, with the labels that each got.

#4512 Kill The Lounge process when ident can't start up
  src/identification.js
  src/server.js
Labels: Type: Bug

#4508 cli: don't error if the user folder doesn't exist
  src/clientManager.js
  src/command-line/users/list.js
Labels: Type: Bug

#4507 User: fix file permissions on create
  src/clientManager.js
  src/command-line/start.js
  src/command-line/users/reset.js
Labels: Type: Feature

#4506 Plugins: include pre-releases in compatibility lookup
  src/plugins/packages/index.js
Labels: Type: Bug

#4487 sqlite: Escape '%' and '_' in search queries.
  src/plugins/messageStorage/sqlite.js
  test/plugins/sqlite.js
Labels: Type: Bug

#4495 set 'video/quicktime' to 'video/mp4' for uploads
  src/plugins/uploader.js
Labels: Type: Bug

#4493 Autocomplete: update to @textcomplete package and close on blur
  client/components/ChatInput.vue
  client/js/autocompletion.js
  package.json
  yarn.lock
Labels: Type: Dependencies

#4536 Update sqlite3 to 5.0.3
  package.json
  yarn.lock
Labels: Type: Dependencies

#4540 Pull in SortableJS from NPM again.
  package.json
  yarn.lock
Labels: Type: Dependencies

#4539 Fix the alignment of the header buttons
  client/css/style.css
Labels: Type: Bug, Status: needs-review

#4537 renovate: Disable digest updates
  renovate.json
Labels: Type: Dependencies, Meta: Skip Changelog, Meta: Internal

#4477 Preserve client certificate when TLS is indirectly enabled by a STS policy
  src/models/network.js
  test/fixtures/env.js
  test/models/network.js
Labels: Type: Bug, Status: needs-review

#4524 Add `prefetchTimeout` config setting
  defaults/config.js
  src/plugins/irc-events/link.js
Labels: Type: Feature, Status: needs-review

#4549 enable znc/playback even without message storage
  src/models/chan.js
  src/models/network.js
Labels: Type: Bug

#4552 Remove node 12, add node 18
  .github/workflows/build.yml
  package.json
Labels: Meta: Internal
