Repository thelounge/thelounge, pull requests merged in 2023-06, with the labels that each got.

#4705 Framework internals
  server/models/network.ts
  server/plugins/inputs/connect.ts
  server/plugins/inputs/nick.ts
  server/plugins/inputs/part.ts
  server/plugins/inputs/raw.ts
Labels: Meta: Internal, Status: needs-review

#4743 Add comments explaining behavior when echo-message is not available
  server/plugins/inputs/action.ts
  server/plugins/inputs/msg.ts
  server/plugins/inputs/notice.ts
Labels: Meta: Internal

#4744 Fix semver for prerelease versions
  server/command-line/install.ts
Labels: Status: release-after-next
