Repository thelounge/thelounge, pull requests merged in 2023-04, with the labels that each got.

#4710 Fix load of channels from user config
  server/client.ts
  test/client.ts
Labels: Type: Bug

#4721 Unbreak nick colors for existing themes
  client/components/Chat.vue
Labels: Meta: Internal, Status: needs-review

#4726 fix motd display to match settings
  client/components/Chat.vue
Labels: Type: Bug

#4724 Publish to npm with provenance
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: Meta: Internal
